// Mock data for Admin Dashboard development
import type {
  TeamMember,
  Template,
  Integration,
  IntegrationLog,
  AnalyticsMetrics,
  RevenueData,
  UserActivityData,
  IntegrationHealth,
  AuditLog,
} from "@/types/admin";

export const mockTeamMembers: TeamMember[] = [
  {
    id: "1",
    email: "admin@example.com",
    full_name: "Admin User",
    avatar_url: "https://github.com/shadcn.png",
    role: "admin",
    status: "active",
    created_at: "2025-01-01T00:00:00Z",
    last_login: "2025-10-19T10:30:00Z",
  },
  {
    id: "2",
    email: "manager@example.com",
    full_name: "Project Manager",
    avatar_url: undefined,
    role: "manager",
    status: "active",
    created_at: "2025-01-15T00:00:00Z",
    last_login: "2025-10-19T09:15:00Z",
  },
  {
    id: "3",
    email: "dev1@example.com",
    full_name: "John Developer",
    avatar_url: undefined,
    role: "developer",
    status: "active",
    created_at: "2025-02-01T00:00:00Z",
    last_login: "2025-10-18T16:45:00Z",
  },
  {
    id: "4",
    email: "dev2@example.com",
    full_name: "Jane Coder",
    avatar_url: undefined,
    role: "developer",
    status: "active",
    created_at: "2025-02-15T00:00:00Z",
    last_login: "2025-10-19T08:00:00Z",
  },
  {
    id: "5",
    email: "client@example.com",
    full_name: "Client User",
    avatar_url: undefined,
    role: "client",
    status: "pending",
    created_at: "2025-10-18T00:00:00Z",
    last_login: undefined,
  },
];

export const mockTemplates: Template[] = [
  {
    id: "1",
    name: "Standard Proposal Template",
    type: "proposal",
    description: "Default template for project proposals with standard sections",
    content: "# Proposal for {{client_name}}\n\n## Project Overview\n{{project_description}}\n\n## Timeline\n{{timeline}}\n\n## Budget\n{{budget}}",
    variables: ["client_name", "project_description", "timeline", "budget"],
    created_by: "1",
    created_at: "2025-01-10T00:00:00Z",
    updated_at: "2025-03-15T00:00:00Z",
    is_active: true,
  },
  {
    id: "2",
    name: "SoW - Web Development",
    type: "sow",
    description: "Statement of Work template for web development projects",
    content: "# Statement of Work\n\n## Scope\n{{scope}}\n\n## Deliverables\n{{deliverables}}\n\n## Payment Terms\n{{payment_terms}}",
    variables: ["scope", "deliverables", "payment_terms"],
    created_by: "1",
    created_at: "2025-01-20T00:00:00Z",
    updated_at: "2025-02-10T00:00:00Z",
    is_active: true,
  },
  {
    id: "3",
    name: "Task Template - Feature Development",
    type: "task",
    description: "Template for feature development tasks",
    content: "## Task: {{task_name}}\n\n### Description\n{{description}}\n\n### Acceptance Criteria\n{{acceptance_criteria}}",
    variables: ["task_name", "description", "acceptance_criteria"],
    created_by: "2",
    created_at: "2025-02-05T00:00:00Z",
    updated_at: "2025-02-05T00:00:00Z",
    is_active: true,
  },
  {
    id: "4",
    name: "Standard Contract",
    type: "contract",
    description: "Standard service contract template",
    content: "# Service Agreement\n\nThis agreement is between {{company_name}} and {{client_name}}...",
    variables: ["company_name", "client_name"],
    created_by: "1",
    created_at: "2025-01-05T00:00:00Z",
    updated_at: "2025-01-05T00:00:00Z",
    is_active: true,
  },
];

export const mockIntegrations: Integration[] = [
  {
    id: "1",
    name: "GitHub",
    type: "github",
    status: "connected",
    connected_at: "2025-01-15T00:00:00Z",
    last_sync: "2025-10-19T10:00:00Z",
    config: { org: "example-org" },
    health_status: "healthy",
  },
  {
    id: "2",
    name: "Vercel",
    type: "vercel",
    status: "connected",
    connected_at: "2025-02-01T00:00:00Z",
    last_sync: "2025-10-19T09:30:00Z",
    config: { team: "example-team" },
    health_status: "healthy",
  },
  {
    id: "3",
    name: "Google Calendar",
    type: "google",
    status: "connected",
    connected_at: "2025-01-20T00:00:00Z",
    last_sync: "2025-10-19T08:00:00Z",
    config: {},
    health_status: "warning",
    error_message: "Token refresh needed",
  },
  {
    id: "4",
    name: "QuickBooks",
    type: "quickbooks",
    status: "error",
    connected_at: "2025-03-01T00:00:00Z",
    last_sync: "2025-10-15T00:00:00Z",
    config: {},
    health_status: "error",
    error_message: "Authentication failed",
  },
  {
    id: "5",
    name: "Stripe",
    type: "stripe",
    status: "connected",
    connected_at: "2025-01-10T00:00:00Z",
    last_sync: "2025-10-19T10:15:00Z",
    config: {},
    health_status: "healthy",
  },
];

export const mockIntegrationLogs: IntegrationLog[] = [
  {
    id: "1",
    integration_id: "1",
    integration_name: "GitHub",
    event_type: "sync",
    message: "Successfully synced 15 repositories",
    created_at: "2025-10-19T10:00:00Z",
  },
  {
    id: "2",
    integration_id: "2",
    integration_name: "Vercel",
    event_type: "sync",
    message: "Deployment status updated for 3 projects",
    created_at: "2025-10-19T09:30:00Z",
  },
  {
    id: "3",
    integration_id: "4",
    integration_name: "QuickBooks",
    event_type: "error",
    message: "Failed to sync invoices: Authentication error",
    details: { error_code: "AUTH_FAILED" },
    created_at: "2025-10-19T09:00:00Z",
  },
  {
    id: "4",
    integration_id: "5",
    integration_name: "Stripe",
    event_type: "sync",
    message: "Payment webhooks processed successfully",
    created_at: "2025-10-19T08:45:00Z",
  },
  {
    id: "5",
    integration_id: "3",
    integration_name: "Google Calendar",
    event_type: "sync",
    message: "Calendar events synced",
    created_at: "2025-10-19T08:00:00Z",
  },
];

export const mockAnalyticsMetrics: AnalyticsMetrics = {
  total_users: 25,
  active_users: 18,
  total_projects: 45,
  active_projects: 12,
  total_revenue: 485000,
  monthly_revenue: 48500,
  revenue_growth: 12.5,
  total_proposals: 67,
  proposals_accepted: 45,
  proposals_pending: 5,
  acceptance_rate: 67.2,
  average_project_value: 10777,
  total_time_tracked: 3420,
  billable_hours: 2890,
};

export const mockRevenueData: RevenueData[] = [
  { month: "Jan", revenue: 35000, projects: 8 },
  { month: "Feb", revenue: 42000, projects: 10 },
  { month: "Mar", revenue: 38000, projects: 9 },
  { month: "Apr", revenue: 45000, projects: 11 },
  { month: "May", revenue: 52000, projects: 12 },
  { month: "Jun", revenue: 48000, projects: 10 },
  { month: "Jul", revenue: 55000, projects: 13 },
  { month: "Aug", revenue: 50000, projects: 11 },
  { month: "Sep", revenue: 58000, projects: 14 },
  { month: "Oct", revenue: 48500, projects: 12 },
];

export const mockUserActivityData: UserActivityData[] = Array.from({ length: 30 }, (_, i) => ({
  date: new Date(2025, 9, i + 1).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
  active_users: Math.floor(Math.random() * 10) + 12,
  new_users: Math.floor(Math.random() * 3),
}));

export const mockIntegrationHealth: IntegrationHealth[] = [
  {
    integration_name: "GitHub",
    status: "healthy",
    uptime_percentage: 99.9,
  },
  {
    integration_name: "Vercel",
    status: "healthy",
    uptime_percentage: 99.8,
  },
  {
    integration_name: "Google Calendar",
    status: "warning",
    uptime_percentage: 95.5,
    last_error: "Token refresh needed",
  },
  {
    integration_name: "QuickBooks",
    status: "error",
    uptime_percentage: 85.2,
    last_error: "Authentication failed",
  },
  {
    integration_name: "Stripe",
    status: "healthy",
    uptime_percentage: 99.95,
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: "1",
    user_id: "1",
    user_name: "Admin User",
    action: "create_user",
    resource_type: "user",
    resource_id: "5",
    details: { email: "client@example.com", role: "client" },
    ip_address: "192.168.1.100",
    created_at: "2025-10-19T10:30:00Z",
  },
  {
    id: "2",
    user_id: "2",
    user_name: "Project Manager",
    action: "update_project",
    resource_type: "project",
    resource_id: "12",
    details: { status: "active" },
    ip_address: "192.168.1.101",
    created_at: "2025-10-19T10:15:00Z",
  },
  {
    id: "3",
    user_id: "1",
    user_name: "Admin User",
    action: "create_template",
    resource_type: "template",
    resource_id: "4",
    details: { name: "Standard Contract", type: "contract" },
    ip_address: "192.168.1.100",
    created_at: "2025-10-19T09:45:00Z",
  },
  {
    id: "4",
    user_id: "3",
    user_name: "John Developer",
    action: "view_proposal",
    resource_type: "proposal",
    resource_id: "23",
    ip_address: "192.168.1.102",
    created_at: "2025-10-19T09:30:00Z",
  },
  {
    id: "5",
    user_id: "1",
    user_name: "Admin User",
    action: "delete_integration",
    resource_type: "integration",
    resource_id: "6",
    details: { integration_name: "GitLab" },
    ip_address: "192.168.1.100",
    created_at: "2025-10-19T09:00:00Z",
  },
  {
    id: "6",
    user_id: "2",
    user_name: "Project Manager",
    action: "update_user_role",
    resource_type: "user",
    resource_id: "3",
    details: { old_role: "developer", new_role: "manager" },
    ip_address: "192.168.1.101",
    created_at: "2025-10-19T08:30:00Z",
  },
];
